### ISSUE TITLE
getting plugin 500 gateway timeout in backstage

### ISSUE THREAD

**Issue by uover822** [K-Phoen/backstage-plugin-grafana#48]
Hi :-) I'm currently getting a 500 gateway timeout in backstage after deploying the plugin to a/ the sample application:
_GET http://localhost:7007/api/proxy/grafana/api/api/alerts?dashboardTag=my-tag 500 (Internal Server Error)_

I've followed the installation steps, as: https://github.com/K-Phoen/backstage-plugin-grafana/blob/main/docs/index.md#installation
and my proxy settings look like:
proxy:
  _&emsp;'/grafana/api':
    &emsp;&emsp;# May be a public or an internal DNS
    &emsp;&emsp;target: http://grafana.host:8080/
    &emsp;&emsp;headers:
        &emsp;&emsp;&emsp;Authorization: Bearer ${GRAFANA_TOKEN}
grafana:
    &emsp;domain: http://localhost:8080_

And my prometheus/ grafana is locally hosted/ localhost.

It seems proxy-related but I'm not sure. Has anyone seen/ have related ideas on this? Do I need to adopt certain host/ port conventions?

Thanks :-)

**Comment by wpessers** [comment]
I'm also getting a 500 _internal servor error_ that seems to be proxy-related. When enabling debug logging I see that my backstage backend encounters the following error: 
`proxy error [HPM] Error occurred while proxying request localhost:7007/api/proxy/grafana/api/search?type=dash-db&tag=my-tag to https://grafana.mycompany.com/ [UNABLE_TO_GET_ISSUER_CERT_LOCALLY] (https://nodejs.org/api/errors.html#errors_common_system_errors) type=plugin`

**Comment by wpessers** [comment]
Found a solution. For anyone running into this issue I would advise taking a look at: https://github.com/chimurai/http-proxy-middleware and more specifically the different http-proxy options in the docs.

**Comment by K-Phoen** [comment]
+1 with @wpessers ↑

This plugin doesn't provide any backend component, so a 500 is unlikely to be related to it.

Wild guess: self-signed certificates might need some specific configuration at the proxy level to be trusted
