### ISSUE TITLE
Support multiple tags + AND/OR behavior

### ISSUE THREAD

**Issue by arnouthoebreckx** [K-Phoen/backstage-plugin-grafana#50]
Hi,

We would like to set multiple dashboards + some generic ones on each of our components, this would require us to use multiple tags that act as OR to display these dashboards that use different tags.

e.g.

```
genericdash1 with tags: generic
genericdash2 with tags: generic
specificAdash with tags: specificA
specificBdash with tags: specificB
```

For component specificA and component specificB we would like to display their own dashboard with corresponding tag but also the generic one. Instead of adding the specific[A-Z] tag to the generic dashboards, I would suggest adding some extra logic to handle a list of tags as an OR operation to display multiple dashboards.

We can also use this suggestion to allow the declaration of multiple tags e.g. `/api/search?tag=app&tag=specificA` that by default works in an AND way in the Grafana API.

Simple suggestion as example but could definitely use feedback:

```
grafana/tag-selector: "specificA, generic"
grafana/method: "OR"
```

**Comment by arnouthoebreckx** [comment]
Pull request already open for this feature

**Comment by jobosk** [comment]
I would love to see this feature happen. If anything, I'd write that within the same annotation, like:

`(tagA or tagB) and tagC`

maybe

`(tagA | tagB) & tagC`

But anyway, thanks for the great work!

**Comment by jobosk** [comment]
I did what I requested :P @K-Phoen would you be kind enough to review?
